#!/usr/bin/env python3
"""
VIX Term Structure Monitor - Main execution script.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict
import pandas as pd

from vix_scraper import VIXScraper, create_fake_data
from term_structure import TermStructureAnalyzer
from visualizer import VIXVisualizer
from alerts import VIXAlertSystem
from file_manager import file_manager


def create_readable_summary(analysis_results: Dict, futures_data: pd.DataFrame) -> str:
    """Create a human-readable summary report."""
    
    timestamp = analysis_results['timestamp']
    date_str = timestamp[:10]
    time_str = timestamp[11:16]
    
    spot_vix = analysis_results['spot_vix']
    points_spreads = analysis_results.get('points_spreads', {})
    roll_carry = analysis_results.get('roll_carry', {})
    inversions = analysis_results.get('inversions', [])
    
    # Create the summary
    summary = f"""VIX Term Structure Summary - {date_str} {time_str}
{'=' * 50}

MARKET OVERVIEW
VIX Spot: {spot_vix:.2f}
Number of Contracts: {len(futures_data)}
Curve Shape: {analysis_results.get('curve_shape', 'N/A')}
Trading Signal: {analysis_results.get('trading_signal', 'N/A')}

POINTS ANALYSIS
Spot to Front Month: {points_spreads.get('spot_to_front', 0):.2f} points
Front to Second Month: {points_spreads.get('front_to_second', 0):.2f} points
"""

    # Add contango/backwardation status
    spot_to_front = points_spreads.get('spot_to_front', 0)
    if spot_to_front > 0:
        summary += f"Status: CONTANGO (+{spot_to_front:.2f} pts)\n"
    elif spot_to_front < 0:
        summary += f"Status: BACKWARDATION ({spot_to_front:.2f} pts)\n"
    else:
        summary += "Status: FLAT\n"

    # Roll carry section
    summary += f"""
ROLL CARRY ANALYSIS
Synthetic 30-Day Index: {roll_carry.get('synthetic_index', 0):.2f}
Roll Points: {roll_carry.get('roll_pts', 0):.4f}
Roll Carry: {roll_carry.get('roll_pct', 0):.2f}%
"""

    # Inversions section
    if inversions:
        summary += f"\nINVERSIONS DETECTED ({len(inversions)})\n"
        for i, inv in enumerate(inversions, 1):
            summary += f"{i}. {inv['contract1']} ({inv['price1']:.2f}) > {inv['contract2']} ({inv['price2']:.2f}) by {inv['magnitude']:.2f} pts\n"
    else:
        summary += "\nINVERSIONS\nNone - Clean term structure\n"

    # Futures contracts section
    summary += f"\nFUTURES CONTRACTS\n"
    for _, row in futures_data.iterrows():
        summary += f"{row['symbol']:<8} {row['price']:>7.2f}  ({row['days_to_expiration']:>3d} days)\n"

    summary += f"\n{'=' * 50}\nGenerated by VIX Term Structure Monitor\n"
    
    return summary


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(description='VIX Term Structure Monitor')
    parser.add_argument('--fake-data', action='store_true', 
                       help='Use fake data for testing instead of scraping')
    parser.add_argument('--no-plot', action='store_true',
                       help='Skip plotting (useful for automated runs)')
    parser.add_argument('--save-plots', action='store_true',
                       help='Save plots to organized output directories')
    parser.add_argument('--config', type=str, default='config.json',
                       help='Path to configuration file')
    parser.add_argument('--save-data', action='store_true',
                       help='Save analysis results to organized output directories')
    parser.add_argument('--headless', action='store_true', default=True,
                       help='Run browser in headless mode (default: True)')
    parser.add_argument('--info', action='store_true',
                       help='Show information about output files and directories')
    parser.add_argument('--cleanup', type=int, metavar='DAYS',
                       help='Clean up files older than DAYS (default: no cleanup)')
    
    args = parser.parse_args()
    
    # Handle info and cleanup options
    if args.info:
        info = file_manager.get_file_info()
        print("📁 VIX Monitor File Information")
        print("=" * 40)
        print(f"Base directory: {info['directories']['base']}")
        print(f"Charts: {info['file_counts']['charts']} files")
        print(f"Data: {info['file_counts']['data']} files") 
        print(f"Logs: {info['file_counts']['logs']} files")
        print(f"Total size: {info['total_size_mb']} MB")
        print("\nRecent files:")
        for file_path in file_manager.list_recent_files(limit=5):
            print(f"  {file_path}")
        return
    
    if args.cleanup:
        print(f"🧹 Cleaning up files older than {args.cleanup} days...")
        file_manager.cleanup_old_files(args.cleanup)
        print("✅ Cleanup complete!")
        return
    
    print("🔍 VIX Term Structure Monitor")
    print("=" * 40)
    print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # Get data
        if args.fake_data:
            print("📊 Using fake data for testing...")
            spot_vix = 22.5
            futures_data = create_fake_data()
        else:
            print("🌐 Scraping live data from CBOE...")
            scraper = VIXScraper(headless=args.headless)
            
            # Get spot VIX
            spot_vix = scraper.get_spot_vix()
            if spot_vix is None:
                print("❌ Failed to get VIX spot price")
                sys.exit(1)
            
            # Get futures data
            futures_data = scraper.get_vix_futures()
            if futures_data is None or futures_data.empty:
                print("❌ Failed to get VIX futures data")
                sys.exit(1)
        
        print(f"✅ VIX Spot: {spot_vix:.2f}")
        print(f"✅ Futures contracts: {len(futures_data)}")
        
        # Analyze term structure
        print("\n📈 Analyzing term structure...")
        analyzer = TermStructureAnalyzer(spot_vix, futures_data)
        analysis_results = analyzer.get_term_structure_summary()
        
        # Display key results
        print(f"\n📋 Analysis Results:")
        points_spreads = analysis_results.get('points_spreads', {})
        roll_carry = analysis_results.get('roll_carry', {})
        print(f"   Spot to Front: {points_spreads.get('spot_to_front', 'N/A')} points")
        print(f"   Front to Second: {points_spreads.get('front_to_second', 'N/A')} points") 
        print(f"   Roll Carry: {roll_carry.get('roll_pct', 'N/A')}%")
        print(f"   Curve Shape: {analysis_results['curve_shape']}")
        print(f"   Trading Signal: {analysis_results['trading_signal']}")
        
        if analysis_results['inversions']:
            print(f"   ⚠️  Inversions: {len(analysis_results['inversions'])}")
        
        # Check alerts
        alert_system = VIXAlertSystem(args.config if Path(args.config).exists() else None)
        alerts = alert_system.check_alerts(analysis_results)
        
        if alerts:
            alert_system.send_alerts(alerts, analysis_results)
            alert_system.log_alert_history(alerts, analysis_results)
        else:
            print("\n✅ No alerts triggered")
        
        # Create visualizations
        if not args.no_plot:
            print("\n📊 Creating comprehensive dashboard...")
            visualizer = VIXVisualizer()
            
            # Determine save paths
            if args.save_plots:
                dashboard_path = file_manager.get_dashboard_path(test_mode=args.fake_data)
                show_plot = False
            else:
                dashboard_path = None
                show_plot = True
            
            # Create comprehensive dashboard with all metrics and term structure
            fig = visualizer.create_comprehensive_dashboard(
                spot_vix, futures_data, analysis_results,
                save_path=dashboard_path
            )
            
            if show_plot:
                fig.show()
            
            # Save dashboard if requested
            if args.save_plots:
                print(f"💾 Dashboard saved:")
                print(f"   📊 Dashboard: {dashboard_path}")
        
        # Save human-readable summary
        if args.save_data:
            # Change extension from .json to .txt for summary
            data_path = file_manager.get_data_path("summary", test_mode=args.fake_data)
            data_path = data_path.replace('.json', '.txt')
            
            summary_text = create_readable_summary(analysis_results, futures_data)
            with open(data_path, 'w') as f:
                f.write(summary_text)
            print(f"💾 Summary report saved to: {data_path}")
        
        print("\n✅ Analysis complete!")
        
    except KeyboardInterrupt:
        print("\n⏹️  Interrupted by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)


def run_daily_monitor():
    """Run daily monitoring with organized file output."""
    
    try:
        # Get organized file paths
        _, dashboard_path, data_path = file_manager.get_daily_report_paths(test_mode=False)
        
        # Run analysis
        scraper = VIXScraper(headless=True)
        spot_vix = scraper.get_spot_vix()
        futures_data = scraper.get_vix_futures()
        
        if spot_vix is None or futures_data is None:
            print("Failed to get market data")
            return False
        
        analyzer = TermStructureAnalyzer(spot_vix, futures_data)
        results = analyzer.get_term_structure_summary()
        
        # Create visualizations
        visualizer = VIXVisualizer()
        visualizer.create_comprehensive_dashboard(spot_vix, futures_data, results, dashboard_path)
        
        # Check alerts
        alert_system = VIXAlertSystem()
        alerts = alert_system.check_alerts(results)
        alert_system.send_alerts(alerts, results)
        alert_system.log_alert_history(alerts, results)
        
        # Save results  
        data_path = data_path.replace('.json', '.txt')
        summary_text = create_readable_summary(results, futures_data)
        with open(data_path, 'w') as f:
            f.write(summary_text)
        
        print(f"Daily monitoring complete. Files saved:")
        print(f"  📊 Dashboard: {dashboard_path}")
        print(f"  📄 Data: {data_path}")
        return True
        
    except Exception as e:
        print(f"Daily monitoring failed: {e}")
        return False


if __name__ == "__main__":
    main()